[package]
name = "wizardry-host"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = "0.24"
tao = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
